"""Change user ID to random string and add premium fields

Revision ID: f3131d6c8443
Revises: f8bff3bdaaef
Create Date: 2025-07-22 15:19:05.322272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3131d6c8443'
down_revision = 'f8bff3bdaaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
