"""Add premium fields to UserApp

Revision ID: f8bff3bdaaef
Revises: 3a8974aa3fd8
Create Date: 2025-07-22 15:11:18.937035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bff3bdaaef'
down_revision = '3a8974aa3fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('premium_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_app', schema=None) as batch_op:
        batch_op.drop_column('premium_end_date')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
